version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
    depends_on:
      - db
      - jackett
      - transmission
    networks:
      - appnetwork

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - appnetwork

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./jackett_data:/config
      - blackhole:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
    networks:
      - appnetwork


  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - USER=vova
      - PASS=vova12345
    volumes:
      - ./downloads:/downloads
      - transmisson_data:/config
      - watch_folder:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
    networks:
      - appnetwork


volumes:
  postgres_data:
  blackhole:
  watch_folder:
  transmisson_data:

networks:
  appnetwork:
    driver: bridge