"""empty message

Revision ID: 0735d13b71e6
Revises: 7d22ad9e94b3
Create Date: 2024-08-25 21:17:05.599184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0735d13b71e6'
down_revision = '7d22ad9e94b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('parsed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('parsed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
