"""empty message

Revision ID: c2827d600d39
Revises: 9b5ca997de28
Create Date: 2024-08-25 21:22:31.859880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2827d600d39'
down_revision = '9b5ca997de28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('is_folder',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('is_folder',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
