"""empty message

Revision ID: ea63fa0b0540
Revises: 4ac3b767fb88
Create Date: 2024-07-19 18:38:08.194163

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea63fa0b0540'
down_revision = '4ac3b767fb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column(
            'status', existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column(
            'status', existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###
